# Generated by Django 3.2 on 2021-05-17 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_user_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
    ]
